import psycopg2

nri_filename = "data/NRI_Table_Counties.csv"
hospital_filename = "data/Hospitals.csv"

def load_nri(filename):
        conn = psycopg2.connect("host=localhost dbname=hospital user=hospital password=hospital")
        cursor = conn.cursor()
        # creates master table to hold complete NRI dataset, table will be deleted later
        cursor.execute("""CREATE TABLE nri_master(
                oid SMALLINT UNIQUE,
                nriId VARCHAR(20) PRIMARY KEY,
                state VARCHAR(250),
                stateabbrv VARCHAR(20),
                statefips VARCHAR(20),
                county VARCHAR(250),
                countytype VARCHAR(250),
                countyfips VARCHAR(20),
                stcofips VARCHAR(20),
                population INT,
                buildvalue NUMERIC(17,2),
                agrivalue NUMERIC(17,2),
                area NUMERIC,
                riskScore NUMERIC,
                riskRatng VARCHAR(50),
                riskNpctl NUMERIC,
                riskSpctl NUMERIC,
                ealScore NUMERIC,
                ealRatng VARCHAR(50),
                ealNpctl NUMERIC,
                ealSpctl NUMERIC,
                ealValt NUMERIC(17,2),
                ealValb NUMERIC(17,2),
                ealValp NUMERIC,
                ealValpe NUMERIC(17,2),
                ealVala NUMERIC(17,2),
                soviScore NUMERIC,
                soviRatng VARCHAR(50),
                soviNpctl NUMERIC,
                soviSpctl NUMERIC,
                soviValue NUMERIC,
                reslScore NUMERIC,
                reslRatng VARCHAR(50),
                reslNpctl NUMERIC,
                reslSpctl NUMERIC,
                reslValue NUMERIC,
                avlnEvnts NUMERIC(17),
                avlnAfreq NUMERIC,
                avlnExpb NUMERIC(17,2),
                avlnExpp NUMERIC,
                avlnExppe NUMERIC(17,2),
                avlnExpt NUMERIC(17,2),
                avlnHlrb NUMERIC,
                avlnHlrp NUMERIC,
                avlnHlrr VARCHAR(50),
                avlnEalb NUMERIC(17,2),
                avlnEalp NUMERIC,
                avlnEalpe NUMERIC(17,2),
                avlnEalt NUMERIC(17,2),
                avlnEals NUMERIC(17,2),
                avlnEalr VARCHAR(50),
                avlnRisks NUMERIC,
                avlnRiskr VARCHAR(50),
                cfldEvnts NUMERIC(17),
                cfldAfreq NUMERIC,
                cfldExpb NUMERIC(17,2),
                cfldExpp NUMERIC,
                cfldExppe NUMERIC(17,2),
                cfldExpt NUMERIC(17,2),
                cfldHlrb NUMERIC,
                cfldHlrp NUMERIC,
                cfldHlrr VARCHAR(50),
                cfldEalb NUMERIC(17,2),
                cfldEalp NUMERIC,
                cfldEalpe NUMERIC(17,2),
                cfldEalt NUMERIC(17,2),
                cfldEals NUMERIC(17,2),
                cfldEalr VARCHAR(50),
                cfldRisks NUMERIC,
                cfldRiskr VARCHAR(50),
                cwavEvnts NUMERIC(17),
                cwavAfreq NUMERIC,
                cwavExpb NUMERIC(17,2),
                cwavExpp NUMERIC,
                cwavExppe NUMERIC(17,2),
                cwavExpa NUMERIC(17,2),
                cwavExpt NUMERIC(17,2),
                cwavHlrb NUMERIC,
                cwavHlrp NUMERIC,
                cwavHlra NUMERIC,
                cwavHlrr VARCHAR(50),
                cwavEalb NUMERIC(17,2),
                cwavEalp NUMERIC,
                cwavEalpe NUMERIC(17,2),
                cwavEala NUMERIC(17,2),
                cwavEalt NUMERIC(17,2),
                cwavEals NUMERIC(17,2),
                cwavEalr VARCHAR(50),
                cwavRisks NUMERIC,
                cwavRiskr VARCHAR(50),
                drgtEvnts NUMERIC(17),
                drgtAfreq NUMERIC,
                drgtExpa NUMERIC(17,2),
                drgtExpt NUMERIC(17,2),
                drgtHlra NUMERIC,
                drgtHlrr VARCHAR(50),
                drgtEala NUMERIC(17,2),
                drgtEalt NUMERIC(17,2),
                drgtEals NUMERIC(17,2),
                drgtEalr VARCHAR(50),
                drgtRisks NUMERIC,
                drgtRiskr VARCHAR(50),
                erqkEvnts NUMERIC(17),
                erqkAfreq NUMERIC,
                erqkExpb NUMERIC(17,2),
                erqkExpp NUMERIC,
                erqkExppe NUMERIC(17,2),
                erqkExpt NUMERIC(17,2),
                erqkHlrb NUMERIC,
                erqkHlrp NUMERIC,
                erqkHlrr VARCHAR(50),
                erqkEalb NUMERIC(17,2),
                erqkEalp NUMERIC,
                erqkEalpe NUMERIC(17,2),
                erqkEalt NUMERIC(17,2),
                erqkEals NUMERIC(17,2),
                erqkEalr VARCHAR(50),
                erqkRisks NUMERIC,
                erqkRiskr VARCHAR(50),
                hailEvnts NUMERIC(17),
                hailAfreq NUMERIC,
                hailExpb NUMERIC(17,2),
                hailExpp NUMERIC,
                hailExppe NUMERIC(17,2),
                hailExpa NUMERIC(17,2),
                hailExpt NUMERIC(17,2),
                hailHlrb NUMERIC,
                hailHlrp NUMERIC,
                hailHlra NUMERIC,
                hailHlrr VARCHAR(50),
                hailEalb NUMERIC(17,2),
                hailEalp NUMERIC,
                hailEalpe NUMERIC(17,2),
                hailEala NUMERIC(17,2),
                hailEalt NUMERIC(17,2),
                hailEals NUMERIC(17,2),
                hailEalr VARCHAR(50),
                hailRisks NUMERIC,
                hailRiskr VARCHAR(50),
                hwavEvnts NUMERIC(17),
                hwavAfreq NUMERIC,
                hwavExpb NUMERIC(17,2),
                hwavExpp NUMERIC,
                hwavExppe NUMERIC(17,2),
                hwavExpa NUMERIC(17,2),
                hwavExpt NUMERIC(17,2),
                hwavHlrb NUMERIC,
                hwavHlrp NUMERIC,
                hwavHlra NUMERIC,
                hwavHlrr VARCHAR(50),
                hwavEalb NUMERIC(17,2),
                hwavEalp NUMERIC,
                hwavEalpe NUMERIC(17,2),
                hwavEala NUMERIC(17,2),
                hwavEalt NUMERIC(17,2),
                hwavEals NUMERIC(17,2),
                hwavEalr VARCHAR(50),
                hwavRisks NUMERIC,
                hwavRiskr VARCHAR(50),
                hrcnEvnts NUMERIC(17),
                hrcnAfreq NUMERIC,
                hrcnExpb NUMERIC(17,2),
                hrcnExpp NUMERIC,
                hrcnExppe NUMERIC(17,2),
                hrcnExpa NUMERIC(17,2),
                hrcnExpt NUMERIC(17,2),
                hrcnHlrb NUMERIC,
                hrcnHlrp NUMERIC,
                hrcnHlra NUMERIC,
                hrcnHlrr VARCHAR(50),
                hrcnEalb NUMERIC(17,2),
                hrcnEalp NUMERIC,
                hrcnEalpe NUMERIC(17,2),
                hrcnEala NUMERIC(17,2),
                hrcnEalt NUMERIC(17,2),
                hrcnEals NUMERIC(17,2),
                hrcnEalr VARCHAR(50),
                hrcnRisks NUMERIC,
                hrcnRiskr VARCHAR(50),
                istmEvnts NUMERIC(17),
                istmAfreq NUMERIC,
                istmExpb NUMERIC(17,2),
                istmExpp NUMERIC,
                istmExppe NUMERIC(17,2),
                istmExpt NUMERIC(17,2),
                istmHlrb NUMERIC,
                istmHlrp NUMERIC,
                istmHlrr VARCHAR(50),
                istmEalb NUMERIC(17,2),
                istmEalp NUMERIC,
                istmEalpe NUMERIC(17,2),
                istmEalt NUMERIC(17,2),
                istmEals NUMERIC(17,2),
                istmEalr VARCHAR(50),
                istmRisks NUMERIC,
                istmRiskr VARCHAR(50),
                lndsEvnts NUMERIC(17),
                lndsAfreq NUMERIC,
                lndsExpb NUMERIC(17,2),
                lndsExpp NUMERIC,
                lndsExppe NUMERIC(17,2),
                lndsExpt NUMERIC(17,2),
                lndsHlrb NUMERIC,
                lndsHlrp NUMERIC,
                lndsHlrr VARCHAR(50),
                lndsEalb NUMERIC(17,2),
                lndsEalp NUMERIC,
                lndsEalpe NUMERIC(17,2),
                lndsEalt NUMERIC(17,2),
                lndsEals NUMERIC(17,2),
                lndsEalr VARCHAR(50),
                lndsRisks NUMERIC,
                lndsRiskr VARCHAR(50),
                ltngEvnts NUMERIC(17),
                ltngAfreq NUMERIC,
                ltngExpb NUMERIC(17,2),
                ltngExpp NUMERIC,
                ltngExppe NUMERIC(17,2),
                ltngExpt NUMERIC(17,2),
                ltngHlrb NUMERIC,
                ltngHlrp NUMERIC,
                ltngHlrr VARCHAR(50),
                ltngEalb NUMERIC(17,2),
                ltngEalp NUMERIC,
                ltngEalpe NUMERIC(17,2),
                ltngEalt NUMERIC(17,2),
                ltngEals NUMERIC(17,2),
                ltngEalr VARCHAR(50),
                ltngRisks NUMERIC,
                ltngRiskr VARCHAR(50),
                rfldEvnts NUMERIC(17),
                rfldAfreq NUMERIC,
                rfldExpb NUMERIC(17,2),
                rfldExpp NUMERIC,
                rfldExppe NUMERIC(17,2),
                rfldExpa NUMERIC(17,2),
                rfldExpt NUMERIC(17,2),
                rfldHlrb NUMERIC,
                rfldHlrp NUMERIC,
                rfldHlra NUMERIC,
                rfldHlrr VARCHAR(50),
                rfldEalb NUMERIC(17,2),
                rfldEalp NUMERIC,
                rfldEalpe NUMERIC(17,2),
                rfldEala NUMERIC(17,2),
                rfldEalt NUMERIC(17,2),
                rfldEals NUMERIC(17,2),
                rfldEalr VARCHAR(50),
                rfldRisks NUMERIC,
                rfldRiskr VARCHAR(50),
                swndEvnts NUMERIC(17),
                swndAfreq NUMERIC,
                swndExpb NUMERIC(17,2),
                swndExpp NUMERIC,
                swndExppe NUMERIC(17,2),
                swndExpa NUMERIC(17,2),
                swndExpt NUMERIC(17,2),
                swndHlrb NUMERIC,
                swndHlrp NUMERIC,
                swndHlra NUMERIC,
                swndHlrr VARCHAR(50),
                swndEalb NUMERIC(17,2),
                swndEalp NUMERIC,
                swndEalpe NUMERIC(17,2),
                swndEala NUMERIC(17,2),
                swndEalt NUMERIC(17,2),
                swndEals NUMERIC(17,2),
                swndEalr VARCHAR(50),
                swndRisks NUMERIC,
                swndRiskr VARCHAR(50),
                trndEvnts NUMERIC(17),
                trndAfreq NUMERIC,
                trndExpb NUMERIC(17,2),
                trndExpp NUMERIC,
                trndExppe NUMERIC(17,2),
                trndExpa NUMERIC(17,2),
                trndExpt NUMERIC(17,2),
                trndHlrb NUMERIC,
                trndHlrp NUMERIC,
                trndHlra NUMERIC,
                trndHlrr VARCHAR(50),
                trndEalb NUMERIC(17,2),
                trndEalp NUMERIC,
                trndEalpe NUMERIC(17,2),
                trndEala NUMERIC(17,2),
                trndEalt NUMERIC(17,2),
                trndEals NUMERIC(17,2),
                trndEalr VARCHAR(50),
                trndRisks NUMERIC,
                trndRiskr VARCHAR(50),
                tsunEvnts NUMERIC(17),
                tsunAfreq NUMERIC,
                tsunExpb NUMERIC(17,2),
                tsunExpp NUMERIC,
                tsunExppe NUMERIC(17,2),
                tsunExpt NUMERIC(17,2),
                tsunHlrb NUMERIC,
                tsunHlrp NUMERIC,
                tsunHlrr VARCHAR(50),
                tsunEalb NUMERIC(17,2),
                tsunEalp NUMERIC,
                tsunEalpe NUMERIC(17,2),
                tsunEalt NUMERIC(17,2),
                tsunEals NUMERIC(17,2),
                tsunEalr VARCHAR(50),
                tsunRisks NUMERIC,
                tsunRiskr VARCHAR(50),
                vlcnEvnts NUMERIC(17),
                vlcnAfreq NUMERIC,
                vlcnExpb NUMERIC(17,2),
                vlcnExpp NUMERIC,
                vlcnExppe NUMERIC(17,2),
                vlcnExpt NUMERIC(17,2),
                vlcnHlrb NUMERIC,
                vlcnHlrp NUMERIC,
                vlcnHlrr VARCHAR(50),
                vlcnEalb NUMERIC(17,2),
                vlcnEalp NUMERIC,
                vlcnEalpe NUMERIC(17,2),
                vlcnEalt NUMERIC(17,2),
                vlcnEals NUMERIC(17,2),
                vlcnEalr VARCHAR(50),
                vlcnRisks NUMERIC,
                vlcnRiskr VARCHAR(50),
                wfirEvnts NUMERIC(17),
                wfirAfreq NUMERIC,
                wfirExpb NUMERIC(17,2),
                wfirExpp NUMERIC,
                wfirExppe NUMERIC(17,2),
                wfirExpa NUMERIC(17,2),
                wfirExpt NUMERIC(17,2),
                wfirHlrb NUMERIC,
                wfirHlrp NUMERIC,
                wfirHlra NUMERIC,
                wfirHlrr VARCHAR(50),
                wfirEalb NUMERIC(17,2),
                wfirEalp NUMERIC,
                wfirEalpe NUMERIC(17,2),
                wfirEala NUMERIC(17,2),
                wfirEalt NUMERIC(17,2),
                wfirEals NUMERIC(17,2),
                wfirEalr VARCHAR(50),
                wfirRisks NUMERIC,
                wfirRiskr VARCHAR(50),
                wntwEvnts NUMERIC(17),
                wntwAfreq NUMERIC,
                wntwExpb NUMERIC(17,2),
                wntwExpp NUMERIC,
                wntwExppe NUMERIC(17,2),
                wntwExpa NUMERIC(17,2),
                wntwExpt NUMERIC(17,2),
                wntwHlrb NUMERIC,
                wntwHlrp NUMERIC,
                wntwHlra NUMERIC,
                wntwHlrr VARCHAR(50),
                wntwEalb NUMERIC(17,2),
                wntwEalp NUMERIC,
                wntwEalpe NUMERIC(17,2),
                wntwEala NUMERIC(17,2),
                wntwEalt NUMERIC(17,2),
                wntwEals NUMERIC(17,2),
                wntwEalr VARCHAR(50),
                wntwRisks NUMERIC,
                wntwRiskr VARCHAR(50),
                nriVer VARCHAR(50)
        );
        """)
        conn.commit()

        # copies data from NRI_Table_Counties.csv to nri_master table
        with open(filename, 'r') as f:
            next(f)
            cursor.copy_from(f, 'nri_master', sep=',', null="")
        conn.commit()
        f.close()

        # the following SQL statements create and fill normalized tables for the NRI dataset
        cursor.execute("""CREATE TABLE nri_version(
                nriId VARCHAR(20) PRIMARY KEY,
                oid SMALLINT UNIQUE,
                nriVer VARCHAR(50)
        );
        """)
        conn.commit()

        cursor.execute("""INSERT INTO nri_version (nriId, oid, nriVer) SELECT nriId, oid, nriVer FROM nri_master;""")
        conn.commit()

        cursor.execute("""CREATE TABLE nri_state(
                stateabbrv VARCHAR(20) PRIMARY KEY,              
                state VARCHAR(250) UNIQUE,
                statefips VARCHAR(20) UNIQUE
        );
        """)
        conn.commit()

        cursor.execute("""INSERT INTO nri_state (stateabbrv, state, statefips) SELECT DISTINCT stateabbrv, state, statefips FROM nri_master;""")
        conn.commit()

        cursor.execute("""CREATE TABLE nri_county(
                stcofips VARCHAR(20) PRIMARY KEY,
                county VARCHAR(250),
                countytype VARCHAR(250),
                countyfips VARCHAR(20),
                stateabbrv VARCHAR(20) REFERENCES nri_state(stateabbrv)                
        );
        """)
        conn.commit()

        cursor.execute("""INSERT INTO nri_county (stcofips, county, countytype, countyfips, stateabbrv) SELECT stcofips, county, countytype, countyfips,
        stateabbrv FROM nri_master;""")
        conn.commit()

        cursor.execute("""CREATE TABLE nri_demographics(
                nriId VARCHAR(20) PRIMARY KEY REFERENCES nri_version(nriId),
                stcofips VARCHAR(20) REFERENCES nri_county(stcofips),
                population INT,
                buildvalue NUMERIC(17,2),
                agrivalue NUMERIC(17,2),
                area NUMERIC                
        );
        """)
        conn.commit()
        
        cursor.execute("""INSERT INTO nri_demographics (nriId, stcofips, population, buildvalue, agrivalue, area) SELECT nriId, stcofips, population,
        buildvalue, agrivalue, area FROM nri_master;""")
        conn.commit()

        cursor.execute("""CREATE TABLE nri_events(
                nriId VARCHAR(20) PRIMARY KEY REFERENCES nri_version(nriId),
                stcofips VARCHAR(20) REFERENCES nri_county(stcofips),
                avlnEvnts NUMERIC(17),
                avlnAfreq NUMERIC,
                cfldEvnts NUMERIC(17),
                cfldAfreq NUMERIC,
                cwavEvnts NUMERIC(17),
                cwavAfreq NUMERIC,
                drgtEvnts NUMERIC(17),
                drgtAfreq NUMERIC,
                erqkEvnts NUMERIC(17),
                erqkAfreq NUMERIC,
                hailEvnts NUMERIC(17),
                hailAfreq NUMERIC,
                hwavEvnts NUMERIC(17),
                hwavAfreq NUMERIC,
                hrcnEvnts NUMERIC(17),
                hrcnAfreq NUMERIC,
                istmEvnts NUMERIC(17),
                istmAfreq NUMERIC,
                lndsEvnts NUMERIC(17),
                lndsAfreq NUMERIC,
                ltngEvnts NUMERIC(17),
                ltngAfreq NUMERIC,
                rfldEvnts NUMERIC(17),
                rfldAfreq NUMERIC,
                swndEvnts NUMERIC(17),
                swndAfreq NUMERIC,
                trndEvnts NUMERIC(17),
                trndAfreq NUMERIC,
                tsunEvnts NUMERIC(17),
                tsunAfreq NUMERIC,
                vlcnEvnts NUMERIC(17),
                vlcnAfreq NUMERIC,
                wfirEvnts NUMERIC(17),
                wfirAfreq NUMERIC,
                wntwEvnts NUMERIC(17),
                wntwAfreq NUMERIC               
        );
        """)
        conn.commit()

        cursor.execute("""INSERT INTO nri_events (nriId, stcofips, avlnEvnts, avlnAfreq, cfldEvnts, cfldAfreq, cwavEvnts, cwavAfreq, drgtEvnts, drgtAfreq,
        erqkEvnts, erqkAfreq, hailEvnts, hailAfreq, hwavEvnts, hwavAfreq, hrcnEvnts, hrcnAfreq, istmEvnts, istmAfreq, lndsEvnts, lndsAfreq, ltngEvnts,
        ltngAfreq, rfldEvnts, rfldAfreq, swndEvnts, swndAfreq, trndEvnts, trndAfreq, tsunEvnts, tsunAfreq, vlcnEvnts, vlcnAfreq, wfirEvnts, wfirAfreq,
        wntwEvnts, wntwAfreq) SELECT nriId, stcofips, avlnEvnts, avlnAfreq, cfldEvnts, cfldAfreq, cwavEvnts, cwavAfreq, drgtEvnts, drgtAfreq, erqkEvnts,
        erqkAfreq, hailEvnts, hailAfreq, hwavEvnts, hwavAfreq, hrcnEvnts, hrcnAfreq, istmEvnts, istmAfreq, lndsEvnts, lndsAfreq, ltngEvnts, ltngAfreq,
        rfldEvnts, rfldAfreq, swndEvnts, swndAfreq, trndEvnts, trndAfreq, tsunEvnts, tsunAfreq, vlcnEvnts, vlcnAfreq, wfirEvnts, wfirAfreq, wntwEvnts,
        wntwAfreq FROM nri_master;""")
        conn.commit()

        cursor.execute("""CREATE TABLE nri_exposure(
                nriId VARCHAR(20) PRIMARY KEY REFERENCES nri_version(nriId),
                stcofips VARCHAR(20) REFERENCES nri_county(stcofips),
                cwavExpa NUMERIC(17,2),
                drgtExpa NUMERIC(17,2),
                hailExpa NUMERIC(17,2),
                hrcnExpa NUMERIC(17,2),
                hwavExpa NUMERIC(17,2),
                rfldExpa NUMERIC(17,2),
                swndExpa NUMERIC(17,2),
                trndExpa NUMERIC(17,2),
                wfirExpa NUMERIC(17,2),
                wntwExpa NUMERIC(17,2),
                avlnExpb NUMERIC(17,2),
                cfldExpb NUMERIC(17,2),
                cwavExpb NUMERIC(17,2),
                erqkExpb NUMERIC(17,2),
                hailExpb NUMERIC(17,2),
                hrcnExpb NUMERIC(17,2),
                hwavExpb NUMERIC(17,2),
                istmExpb NUMERIC(17,2),
                lndsExpb NUMERIC(17,2),
                ltngExpb NUMERIC(17,2),
                rfldExpb NUMERIC(17,2),
                swndExpb NUMERIC(17,2),
                trndExpb NUMERIC(17,2),
                tsunExpb NUMERIC(17,2),
                vlcnExpb NUMERIC(17,2),
                wfirExpb NUMERIC(17,2),
                wntwExpb NUMERIC(17,2),
                avlnExpp NUMERIC,
                cfldExpp NUMERIC,
                cwavExpp NUMERIC,
                erqkExpp NUMERIC,
                hailExpp NUMERIC,
                hrcnExpp NUMERIC,
                hwavExpp NUMERIC,
                istmExpp NUMERIC,
                lndsExpp NUMERIC,
                ltngExpp NUMERIC,
                rfldExpp NUMERIC,
                swndExpp NUMERIC,
                trndExpp NUMERIC,
                tsunExpp NUMERIC,
                vlcnExpp NUMERIC,
                wfirExpp NUMERIC,
                wntwExpp NUMERIC,
                avlnExppe NUMERIC(17,2),
                cfldExppe NUMERIC(17,2),
                cwavExppe NUMERIC(17,2),
                erqkExppe NUMERIC(17,2),
                hailExppe NUMERIC(17,2),
                hrcnExppe NUMERIC(17,2),
                hwavExppe NUMERIC(17,2),
                istmExppe NUMERIC(17,2),
                lndsExppe NUMERIC(17,2),
                ltngExppe NUMERIC(17,2),
                rfldExppe NUMERIC(17,2),
                swndExppe NUMERIC(17,2),
                trndExppe NUMERIC(17,2),
                tsunExppe NUMERIC(17,2),
                vlcnExppe NUMERIC(17,2),
                wfirExppe NUMERIC(17,2),
                wntwExppe NUMERIC(17,2),
                avlnExpt NUMERIC(17,2),
                cfldExpt NUMERIC(17,2),
                cwavExpt NUMERIC(17,2),
                drgtExpt NUMERIC(17,2),
                erqkExpt NUMERIC(17,2),
                hailExpt NUMERIC(17,2),
                hrcnExpt NUMERIC(17,2),
                hwavExpt NUMERIC(17,2),
                istmExpt NUMERIC(17,2),
                lndsExpt NUMERIC(17,2),
                ltngExpt NUMERIC(17,2),
                rfldExpt NUMERIC(17,2),
                swndExpt NUMERIC(17,2),
                trndExpt NUMERIC(17,2),
                tsunExpt NUMERIC(17,2),
                vlcnExpt NUMERIC(17,2),
                wfirExpt NUMERIC(17,2),
                wntwExpt NUMERIC(17,2)              
        );
        """)
        conn.commit()

        cursor.execute("""INSERT INTO nri_exposure (nriId, stcofips, cwavExpa, drgtExpa, hailExpa, hrcnExpa, hwavExpa, rfldExpa, swndExpa, trndExpa, wfirExpa,
        wntwExpa, avlnExpb, cfldExpb, cwavExpb, erqkExpb, hailExpb, hrcnExpb, hwavExpb, istmExpb, lndsExpb, ltngExpb, rfldExpb, swndExpb, trndExpb,
        tsunExpb, vlcnExpb, wfirExpb, wntwExpb, avlnExpp, cfldExpp, cwavExpp, erqkExpp, hailExpp, hrcnExpp, hwavExpp, istmExpp, lndsExpp, ltngExpp,
        rfldExpp, swndExpp, trndExpp, tsunExpp, vlcnExpp, wfirExpp, wntwExpp, avlnExppe, cfldExppe, cwavExppe, erqkExppe, hailExppe, hrcnExppe, hwavExppe,
        istmExppe, lndsExppe, ltngExppe, rfldExppe, swndExppe, trndExppe, tsunExppe, vlcnExppe, wfirExppe, wntwExppe, avlnExpt, cfldExpt, cwavExpt,
        drgtExpt, erqkExpt, hailExpt, hrcnExpt, hwavExpt, istmExpt, lndsExpt, ltngExpt, rfldExpt, swndExpt, trndExpt, tsunExpt, vlcnExpt, wfirExpt,
        wntwExpt) SELECT nriId, stcofips, cwavExpa, drgtExpa, hailExpa, hrcnExpa, hwavExpa, rfldExpa, swndExpa, trndExpa, wfirExpa, wntwExpa, avlnExpb,
        cfldExpb, cwavExpb, erqkExpb, hailExpb, hrcnExpb, hwavExpb, istmExpb, lndsExpb, ltngExpb, rfldExpb, swndExpb, trndExpb, tsunExpb, vlcnExpb,
        wfirExpb, wntwExpb, avlnExpp, cfldExpp, cwavExpp, erqkExpp, hailExpp, hrcnExpp, hwavExpp, istmExpp, lndsExpp, ltngExpp, rfldExpp, swndExpp,
        trndExpp, tsunExpp, vlcnExpp, wfirExpp, wntwExpp, avlnExppe, cfldExppe, cwavExppe, erqkExppe, hailExppe, hrcnExppe, hwavExppe, istmExppe,
        lndsExppe, ltngExppe, rfldExppe, swndExppe, trndExppe, tsunExppe, vlcnExppe, wfirExppe, wntwExppe, avlnExpt, cfldExpt, cwavExpt, drgtExpt, erqkExpt,
        hailExpt, hrcnExpt, hwavExpt, istmExpt, lndsExpt, ltngExpt, rfldExpt, swndExpt, trndExpt, tsunExpt, vlcnExpt, wfirExpt, wntwExpt FROM nri_master;""")
        conn.commit()

        cursor.execute("""CREATE TABLE nri_historic_loss(
                nriId VARCHAR(20) PRIMARY KEY REFERENCES nri_version(nriId),
                stcofips VARCHAR(20) REFERENCES nri_county(stcofips),
                cwavHlra NUMERIC,
                drgtHlra NUMERIC,
                hailHlra NUMERIC,
                hrcnHlra NUMERIC,
                hwavHlra NUMERIC,
                rfldHlra NUMERIC,
                swndHlra NUMERIC,
                trndHlra NUMERIC,
                wfirHlra NUMERIC,
                wntwHlra NUMERIC,
                avlnHlrb NUMERIC,
                cfldHlrb NUMERIC,
                cwavHlrb NUMERIC,
                erqkHlrb NUMERIC,
                hailHlrb NUMERIC,
                hrcnHlrb NUMERIC,
                hwavHlrb NUMERIC,
                istmHlrb NUMERIC,
                lndsHlrb NUMERIC,
                ltngHlrb NUMERIC,
                rfldHlrb NUMERIC,
                swndHlrb NUMERIC,
                trndHlrb NUMERIC,
                tsunHlrb NUMERIC,
                vlcnHlrb NUMERIC,
                wfirHlrb NUMERIC,
                wntwHlrb NUMERIC,
                avlnHlrp NUMERIC,
                cfldHlrp NUMERIC,
                cwavHlrp NUMERIC,
                erqkHlrp NUMERIC,
                hailHlrp NUMERIC,
                hrcnHlrp NUMERIC,
                hwavHlrp NUMERIC,
                istmHlrp NUMERIC,
                lndsHlrp NUMERIC,
                ltngHlrp NUMERIC,
                rfldHlrp NUMERIC,
                swndHlrp NUMERIC,
                trndHlrp NUMERIC,
                tsunHlrp NUMERIC,
                vlcnHlrp NUMERIC,
                wfirHlrp NUMERIC,
                wntwHlrp NUMERIC,
                avlnHlrr VARCHAR(50),
                cfldHlrr VARCHAR(50),
                cwavHlrr VARCHAR(50),
                drgtHlrr VARCHAR(50),
                erqkHlrr VARCHAR(50),
                hailHlrr VARCHAR(50),
                hrcnHlrr VARCHAR(50),
                hwavHlrr VARCHAR(50),
                istmHlrr VARCHAR(50),
                lndsHlrr VARCHAR(50),
                ltngHlrr VARCHAR(50),
                rfldHlrr VARCHAR(50),
                swndHlrr VARCHAR(50),
                trndHlrr VARCHAR(50),
                tsunHlrr VARCHAR(50),
                vlcnHlrr VARCHAR(50),
                wfirHlrr VARCHAR(50),
                wntwHlrr VARCHAR(50) 
        );
        """)
        conn.commit()

        cursor.execute("""INSERT INTO nri_historic_loss (nriId, stcofips, cwavHlra, drgtHlra, hailHlra, hrcnHlra, hwavHlra, rfldHlra, swndHlra, trndHlra,
        wfirHlra, wntwHlra, avlnHlrb, cfldHlrb, cwavHlrb, erqkHlrb, hailHlrb, hrcnHlrb, hwavHlrb, istmHlrb, lndsHlrb, ltngHlrb, rfldHlrb, swndHlrb,
        trndHlrb, tsunHlrb, vlcnHlrb, wfirHlrb, wntwHlrb, avlnHlrp, cfldHlrp, cwavHlrp, erqkHlrp, hailHlrp, hrcnHlrp, hwavHlrp, istmHlrp, lndsHlrp,
        ltngHlrp, rfldHlrp, swndHlrp, trndHlrp, tsunHlrp, vlcnHlrp, wfirHlrp, wntwHlrp, avlnHlrr, cfldHlrr, cwavHlrr, drgtHlrr, erqkHlrr, hailHlrr,
        hrcnHlrr, hwavHlrr, istmHlrr, lndsHlrr, ltngHlrr, rfldHlrr, swndHlrr, trndHlrr, tsunHlrr, vlcnHlrr, wfirHlrr, wntwHlrr) SELECT nriId, stcofips,
        cwavHlra, drgtHlra, hailHlra, hrcnHlra, hwavHlra, rfldHlra, swndHlra, trndHlra, wfirHlra, wntwHlra, avlnHlrb, cfldHlrb, cwavHlrb, erqkHlrb,
        hailHlrb, hrcnHlrb, hwavHlrb, istmHlrb, lndsHlrb, ltngHlrb, rfldHlrb, swndHlrb, trndHlrb, tsunHlrb, vlcnHlrb, wfirHlrb, wntwHlrb, avlnHlrp,
        cfldHlrp, cwavHlrp, erqkHlrp, hailHlrp, hrcnHlrp, hwavHlrp, istmHlrp, lndsHlrp, ltngHlrp, rfldHlrp, swndHlrp, trndHlrp, tsunHlrp, vlcnHlrp,
        wfirHlrp, wntwHlrp, avlnHlrr, cfldHlrr, cwavHlrr, drgtHlrr, erqkHlrr, hailHlrr, hrcnHlrr, hwavHlrr, istmHlrr, lndsHlrr, ltngHlrr, rfldHlrr,
        swndHlrr, trndHlrr, tsunHlrr, vlcnHlrr, wfirHlrr, wntwHlrr FROM nri_master;""")
        conn.commit()

        cursor.execute("""CREATE TABLE nri_expected_loss(
                nriId VARCHAR(20) PRIMARY KEY REFERENCES nri_version(nriId),
                stcofips VARCHAR(20) REFERENCES nri_county(stcofips),
                ealValt NUMERIC(17,2),
                ealValb NUMERIC(17,2),
                ealValp NUMERIC,
                ealValpe NUMERIC(17,2),
                ealVala NUMERIC(17,2),
                cwavEala NUMERIC(17,2),
                drgtEala NUMERIC(17,2),
                hailEala NUMERIC(17,2),
                hrcnEala NUMERIC(17,2),
                hwavEala NUMERIC(17,2),
                rfldEala NUMERIC(17,2),
                swndEala NUMERIC(17,2),
                trndEala NUMERIC(17,2),
                wfirEala NUMERIC(17,2),
                wntwEala NUMERIC(17,2),
                avlnEalb NUMERIC(17,2),
                cfldEalb NUMERIC(17,2),
                cwavEalb NUMERIC(17,2),
                erqkEalb NUMERIC(17,2),
                hailEalb NUMERIC(17,2),
                hrcnEalb NUMERIC(17,2),
                hwavEalb NUMERIC(17,2),
                istmEalb NUMERIC(17,2),
                lndsEalb NUMERIC(17,2),
                ltngEalb NUMERIC(17,2),
                rfldEalb NUMERIC(17,2),
                swndEalb NUMERIC(17,2),
                trndEalb NUMERIC(17,2),
                tsunEalb NUMERIC(17,2),
                vlcnEalb NUMERIC(17,2),
                wfirEalb NUMERIC(17,2),
                wntwEalb NUMERIC(17,2),
                avlnEalp NUMERIC,
                cfldEalp NUMERIC,
                cwavEalp NUMERIC,
                erqkEalp NUMERIC,
                hailEalp NUMERIC,
                hrcnEalp NUMERIC,
                hwavEalp NUMERIC,
                istmEalp NUMERIC,
                lndsEalp NUMERIC,
                ltngEalp NUMERIC,
                rfldEalp NUMERIC,
                swndEalp NUMERIC,
                trndEalp NUMERIC,
                tsunEalp NUMERIC,
                vlcnEalp NUMERIC,
                wfirEalp NUMERIC,
                wntwEalp NUMERIC,
                avlnEalpe NUMERIC(17,2),
                cfldEalpe NUMERIC(17,2),
                cwavEalpe NUMERIC(17,2),
                erqkEalpe NUMERIC(17,2),
                hailEalpe NUMERIC(17,2),
                hrcnEalpe NUMERIC(17,2),
                hwavEalpe NUMERIC(17,2),
                istmEalpe NUMERIC(17,2),
                lndsEalpe NUMERIC(17,2),
                ltngEalpe NUMERIC(17,2),
                rfldEalpe NUMERIC(17,2),
                swndEalpe NUMERIC(17,2),
                trndEalpe NUMERIC(17,2),
                tsunEalpe NUMERIC(17,2),
                vlcnEalpe NUMERIC(17,2),
                wfirEalpe NUMERIC(17,2),
                wntwEalpe NUMERIC(17,2),
                avlnEalr VARCHAR(50),
                cfldEalr VARCHAR(50),
                cwavEalr VARCHAR(50),
                drgtEalr VARCHAR(50),
                erqkEalr VARCHAR(50),
                hailEalr VARCHAR(50),
                hrcnEalr VARCHAR(50),
                hwavEalr VARCHAR(50),
                istmEalr VARCHAR(50),
                lndsEalr VARCHAR(50),
                ltngEalr VARCHAR(50),
                rfldEalr VARCHAR(50),
                swndEalr VARCHAR(50),
                trndEalr VARCHAR(50),
                tsunEalr VARCHAR(50),
                vlcnEalr VARCHAR(50),
                wfirEalr VARCHAR(50),
                wntwEalr VARCHAR(50),
                avlnEals NUMERIC(17,2),
                cfldEals NUMERIC(17,2),
                cwavEals NUMERIC(17,2),
                drgtEals NUMERIC(17,2),
                erqkEals NUMERIC(17,2),
                hailEals NUMERIC(17,2),
                hrcnEals NUMERIC(17,2),
                hwavEals NUMERIC(17,2),
                istmEals NUMERIC(17,2),
                lndsEals NUMERIC(17,2),
                ltngEals NUMERIC(17,2),
                rfldEals NUMERIC(17,2),
                swndEals NUMERIC(17,2),
                trndEals NUMERIC(17,2),
                tsunEals NUMERIC(17,2),
                vlcnEals NUMERIC(17,2),
                wfirEals NUMERIC(17,2),
                wntwEals NUMERIC(17,2),
                avlnEalt NUMERIC(17,2),
                cfldEalt NUMERIC(17,2),
                cwavEalt NUMERIC(17,2),
                drgtEalt NUMERIC(17,2),
                erqkEalt NUMERIC(17,2),
                hailEalt NUMERIC(17,2),
                hrcnEalt NUMERIC(17,2),
                hwavEalt NUMERIC(17,2),
                istmEalt NUMERIC(17,2),
                lndsEalt NUMERIC(17,2),
                ltngEalt NUMERIC(17,2),
                rfldEalt NUMERIC(17,2),
                swndEalt NUMERIC(17,2),
                trndEalt NUMERIC(17,2),
                tsunEalt NUMERIC(17,2),
                vlcnEalt NUMERIC(17,2),
                wfirEalt NUMERIC(17,2),
                wntwEalt NUMERIC(17,2)
        );
        """)
        conn.commit()

        cursor.execute("""INSERT INTO nri_expected_loss (nriId, stcofips, ealValt, ealValb, ealValp, ealValpe, ealVala, cwavEala, drgtEala, hailEala, hrcnEala, hwavEala, rfldEala, swndEala, trndEala, wfirEala,
        wntwEala, avlnEalb, cfldEalb, cwavEalb, erqkEalb, hailEalb, hrcnEalb, hwavEalb, istmEalb, lndsEalb, ltngEalb, rfldEalb, swndEalb, trndEalb,
        tsunEalb, vlcnEalb, wfirEalb, wntwEalb, avlnEalp, cfldEalp, cwavEalp, erqkEalp, hailEalp, hrcnEalp, hwavEalp, istmEalp, lndsEalp, ltngEalp,
        rfldEalp, swndEalp, trndEalp, tsunEalp, vlcnEalp, wfirEalp, wntwEalp, avlnEalpe, cfldEalpe, cwavEalpe, erqkEalpe, hailEalpe, hrcnEalpe, hwavEalpe,
        istmEalpe, lndsEalpe, ltngEalpe, rfldEalpe, swndEalpe, trndEalpe, tsunEalpe, vlcnEalpe, wfirEalpe, wntwEalpe, avlnEalr, cfldEalr, cwavEalr,
        drgtEalr, erqkEalr, hailEalr, hrcnEalr, hwavEalr, istmEalr, lndsEalr, ltngEalr, rfldEalr, swndEalr, trndEalr, tsunEalr, vlcnEalr, wfirEalr,
        wntwEalr, avlnEals, cfldEals, cwavEals,drgtEals, erqkEals, hailEals, hrcnEals, hwavEals, istmEals, lndsEals, ltngEals, rfldEals, swndEals, trndEals,
        tsunEals, vlcnEals, wfirEals, wntwEals, avlnEalt, cfldEalt, cwavEalt, drgtEalt, erqkEalt, hailEalt, hrcnEalt, hwavEalt, istmEalt, lndsEalt,
        ltngEalt, rfldEalt, swndEalt, trndEalt, tsunEalt, vlcnEalt, wfirEalt, wntwEalt) SELECT nriId, stcofips, ealValt, ealValb, ealValp, ealValpe, ealVala, cwavEala, drgtEala, hailEala, hrcnEala, hwavEala,
        rfldEala, swndEala, trndEala, wfirEala, wntwEala, avlnEalb, cfldEalb, cwavEalb, erqkEalb, hailEalb, hrcnEalb, hwavEalb, istmEalb, lndsEalb, ltngEalb,
        rfldEalb, swndEalb, trndEalb, tsunEalb, vlcnEalb, wfirEalb, wntwEalb, avlnEalp, cfldEalp, cwavEalp, erqkEalp, hailEalp, hrcnEalp, hwavEalp,
        istmEalp, lndsEalp, ltngEalp, rfldEalp, swndEalp, trndEalp, tsunEalp, vlcnEalp, wfirEalp, wntwEalp, avlnEalpe, cfldEalpe, cwavEalpe, erqkEalpe,
        hailEalpe, hrcnEalpe, hwavEalpe, istmEalpe, lndsEalpe, ltngEalpe, rfldEalpe, swndEalpe, trndEalpe, tsunEalpe, vlcnEalpe, wfirEalpe, wntwEalpe,
        avlnEalr, cfldEalr, cwavEalr, drgtEalr, erqkEalr, hailEalr, hrcnEalr, hwavEalr, istmEalr, lndsEalr, ltngEalr, rfldEalr, swndEalr, trndEalr,
        tsunEalr, vlcnEalr, wfirEalr, wntwEalr, avlnEals, cfldEals, cwavEals, drgtEals, erqkEals, hailEals, hrcnEals, hwavEals, istmEals, lndsEals,
        ltngEals, rfldEals, swndEals, trndEals, tsunEals, vlcnEals, wfirEals, wntwEals, avlnEalt, cfldEalt, cwavEalt, drgtEalt, erqkEalt, hailEalt,
        hrcnEalt, hwavEalt, istmEalt, lndsEalt, ltngEalt, rfldEalt, swndEalt, trndEalt, tsunEalt, vlcnEalt, wfirEalt, wntwEalt FROM nri_master;""")
        conn.commit()

        cursor.execute("""CREATE TABLE nri_risk(
                nriId VARCHAR(20) PRIMARY KEY REFERENCES nri_version(nriId),
                stcofips VARCHAR(20) REFERENCES nri_county(stcofips),
                riskRatng VARCHAR(50),
                avlnRiskr VARCHAR(50),
                cfldRiskr VARCHAR(50),
                cwavRiskr VARCHAR(50),
                drgtRiskr VARCHAR(50),
                erqkRiskr VARCHAR(50),
                hailRiskr VARCHAR(50),
                hrcnRiskr VARCHAR(50),
                hwavRiskr VARCHAR(50),
                istmRiskr VARCHAR(50),
                lndsRiskr VARCHAR(50),
                ltngRiskr VARCHAR(50),
                rfldRiskr VARCHAR(50),
                swndRiskr VARCHAR(50),
                trndRiskr VARCHAR(50),
                tsunRiskr VARCHAR(50),
                vlcnRiskr VARCHAR(50),
                wfirRiskr VARCHAR(50),
                wntwRiskr VARCHAR(50),
                riskScore NUMERIC,
                avlnRisks NUMERIC,
                cfldRisks NUMERIC,
                cwavRisks NUMERIC,
                drgtRisks NUMERIC,
                erqkRisks NUMERIC,
                hailRisks NUMERIC,
                hrcnRisks NUMERIC,
                hwavRisks NUMERIC,
                istmRisks NUMERIC,
                lndsRisks NUMERIC,
                ltngRisks NUMERIC,
                rfldRisks NUMERIC,
                swndRisks NUMERIC,
                trndRisks NUMERIC,
                tsunRisks NUMERIC,
                vlcnRisks NUMERIC,
                wfirRisks NUMERIC,
                wntwRisks NUMERIC
        );
        """)
        conn.commit()

        cursor.execute("""INSERT INTO nri_risk (nriId, stcofips, riskScore, riskRatng, avlnRiskr, cfldRiskr, cwavRiskr, drgtRiskr, erqkRiskr, hailRiskr, hrcnRiskr,
        hwavRiskr, istmRiskr, lndsRiskr, ltngRiskr, rfldRiskr, swndRiskr, trndRiskr, tsunRiskr, vlcnRiskr, wfirRiskr, wntwRiskr, avlnRisks, cfldRisks,
        cwavRisks, drgtRisks, erqkRisks, hailRisks, hrcnRisks, hwavRisks, istmRisks, lndsRisks, ltngRisks, rfldRisks, swndRisks, trndRisks, tsunRisks,
        vlcnRisks, wfirRisks, wntwRisks) SELECT nriId, stcofips, riskScore, riskRatng, avlnRiskr, cfldRiskr, cwavRiskr, drgtRiskr, erqkRiskr, hailRiskr, hrcnRiskr,
        hwavRiskr, istmRiskr, lndsRiskr, ltngRiskr, rfldRiskr, swndRiskr, trndRiskr, tsunRiskr, vlcnRiskr, wfirRiskr, wntwRiskr, avlnRisks, cfldRisks,
        cwavRisks, drgtRisks, erqkRisks, hailRisks, hrcnRisks, hwavRisks, istmRisks, lndsRisks, ltngRisks, rfldRisks, swndRisks, trndRisks, tsunRisks,
        vlcnRisks, wfirRisks, wntwRisks FROM nri_master;""")
        conn.commit()

        cursor.execute("""CREATE TABLE nri_percentiles(
                nriId VARCHAR(20) PRIMARY KEY REFERENCES nri_version(nriId),
                stcofips VARCHAR(20) REFERENCES nri_county(stcofips),
                riskNpctl NUMERIC,
                riskSpctl NUMERIC,
                ealNpctl NUMERIC,
                ealSpctl NUMERIC
        );
        """)
        conn.commit()

        cursor.execute("""INSERT INTO nri_percentiles (nriId, stcofips, riskNpctl, riskSpctl, ealNpctl, ealSpctl) SELECT nriId, stcofips, riskNpctl, riskSpctl,
        ealNpctl, ealSpctl FROM nri_master;""")
        conn.commit()

        # the master NRI table is dropped
        cursor.execute("""DROP TABLE nri_master;""")
        conn.commit()
        
        conn.close()

load_nri(nri_filename)

def load_hospital(filename):
        conn = psycopg2.connect("host=localhost dbname=hospital user=hospital password=hospital")
        cursor = conn.cursor()
        # creates master table to hold complete hospital dataset, table will be deleted later
        cursor.execute("""CREATE TABLE hospital_master(
                X DECIMAL(12,4),
                Y DECIMAL(12,4),
                OBJECTID INT UNIQUE,
                ID BIGINT PRIMARY KEY,
                NAME VARCHAR(127),
                ADDRESS VARCHAR(127),
                CITY VARCHAR(30),
                STATE CHAR(2),
                ZIP INT,
                ZIP4 VARCHAR(20),
                TELEPHONE VARCHAR(15),
                TYPE VARCHAR(127),
                STATUS VARCHAR(10),
                POPULATION INT,
                COUNTY VARCHAR(20),
                COUNTYFIPS VARCHAR(20),
                COUNTRY CHAR(3) DEFAULT 'USA',
                LATITUDE DECIMAL(10,4),
                LONGITUDE DECIMAL(11,4),
                NAICS_CODE INT,
                NAICS_DESC VARCHAR(127),
                SOURCE VARCHAR(255),
                SOURCEDATE TIMESTAMP,
                VAL_METHOD VARCHAR(127),
                VAL_DATE TIMESTAMP,
                WEBSITE VARCHAR(255),
                STATE_ID VARCHAR(50),
                ALT_NAME VARCHAR(127),
                ST_FIPS INT,
                OWNER VARCHAR(32),
                TTL_STAFF INT,
                BEDS INT,
                TRAUMA VARCHAR(50),
                HELIPAD CHAR              
        );
        """)
        conn.commit()       

        # copies data from Hospital.csv to hospital_master table
        with open(filename, 'r', encoding='utf-8') as f:
                next(f)
                cursor.copy_expert("copy hospital_master from stdin (format csv)", f)
        conn.commit()
        f.close()

        # the following SQL statements create and fill normalized tables for the hospital dataset
        cursor.execute("""CREATE TABLE hosp_general_info(
                NAME VARCHAR(127),
                ALT_NAME VARCHAR(127),	
                OBJECTID INT UNIQUE,
                ID BIGINT PRIMARY KEY,
                TYPE VARCHAR(127),
                STATUS VARCHAR(10),
                OWNER VARCHAR(32),
                TTL_STAFF INT,	
                TRAUMA VARCHAR(50),
                HELIPAD CHAR,
                BEDS INT,	
                POPULATION INT,	
                NAICS_CODE INT,
                NAICS_DESC VARCHAR(127)
        );
        """)
        conn.commit()

        cursor.execute("""INSERT INTO hosp_general_info (NAME, ALT_NAME, OBJECTID, ID, TYPE, STATUS, OWNER, TTL_STAFF, TRAUMA, HELIPAD, BEDS,
        POPULATION, NAICS_CODE, NAICS_DESC) SELECT NAME, ALT_NAME, OBJECTID, ID, TYPE, STATUS, OWNER, TTL_STAFF, TRAUMA, HELIPAD, BEDS,
        POPULATION, NAICS_CODE, NAICS_DESC FROM hospital_master;""")
        conn.commit()

        cursor.execute("""CREATE TABLE hosp_dataset_info(
                OBJECTID INT REFERENCES hosp_general_info (OBJECTID) ON UPDATE CASCADE ON DELETE CASCADE,
                ID BIGINT REFERENCES hosp_general_info (ID) ON UPDATE CASCADE ON DELETE CASCADE,
                SOURCE VARCHAR(255),
                SOURCEDATE TIMESTAMP,
                VAL_METHOD VARCHAR(127),
                VAL_DATE TIMESTAMP
        );
        """)
        conn.commit()

        cursor.execute("""INSERT INTO hosp_dataset_info (OBJECTID, ID, SOURCE, SOURCEDATE, VAL_METHOD, VAL_DATE) SELECT OBJECTID, ID, SOURCE,
        SOURCEDATE, VAL_METHOD, VAL_DATE FROM hospital_master;""")
        conn.commit()

        cursor.execute("""CREATE TABLE hosp_contact_info(
                OBJECTID INT REFERENCES hosp_general_info (OBJECTID) ON UPDATE CASCADE ON DELETE CASCADE,
                ID BIGINT REFERENCES hosp_general_info (ID) ON UPDATE CASCADE ON DELETE CASCADE,
                TELEPHONE VARCHAR(15),	
                WEBSITE VARCHAR(255)
        );
        """)
        conn.commit()

        cursor.execute("""INSERT INTO hosp_contact_info (OBJECTID, ID, TELEPHONE, WEBSITE) SELECT OBJECTID, ID, TELEPHONE, WEBSITE FROM hospital_master;""")
        conn.commit()

        cursor.execute("""CREATE TABLE hosp_address_info(
                OBJECTID INT REFERENCES hosp_general_info (OBJECTID) ON UPDATE CASCADE ON DELETE CASCADE,    
                ID BIGINT REFERENCES hosp_general_info (ID) ON UPDATE CASCADE ON DELETE CASCADE,
                X DECIMAL(12,4),	
                Y DECIMAL(12,4),
                ADDRESS VARCHAR(127),
                CITY VARCHAR(30),	
                COUNTY VARCHAR(20),	
                COUNTYFIPS VARCHAR(20),
                STATE CHAR(2),
                STATE_ID VARCHAR(50),	
                ST_FIPS INT,
                COUNTRY CHAR(3) DEFAULT 'USA',
                ZIP INT,
                ZIP4 VARCHAR(20),	
                LATITUDE DECIMAL(10,4),
                LONGITUDE DECIMAL(11,4)
        );
        """)
        conn.commit()

        cursor.execute("""INSERT INTO hosp_address_info (OBJECTID, ID, X, Y, ADDRESS, CITY, COUNTY, COUNTYFIPS, STATE, STATE_ID, ST_FIPS, COUNTRY,
        ZIP, ZIP4, LATITUDE, LONGITUDE) SELECT OBJECTID, ID, X, Y, ADDRESS, CITY, COUNTY, COUNTYFIPS, STATE, STATE_ID, ST_FIPS, COUNTRY, ZIP, ZIP4,
        LATITUDE, LONGITUDE FROM hospital_master;""")
        conn.commit()

        # the master hospital table is dropped
        cursor.execute("""DROP TABLE hospital_master;""")
        conn.commit()

        conn.close()

load_hospital(hospital_filename)

def create_user_log():

        # creates tables to log user data
        
        conn = psycopg2.connect("host=localhost dbname=hospital user=hospital password=hospital")
        cursor = conn.cursor()

        cursor.execute("""CREATE TABLE user_data(
                user_name VARCHAR(50) PRIMARY KEY,
                login_count INT
        );
        """)
        conn.commit()

        cursor.execute("""CREATE TABLE user_activity_log(
                user_name VARCHAR(50) REFERENCES User_data(user_name) ON UPDATE CASCADE ON DELETE CASCADE,
                query_run INT,
                tables_accessed VARCHAR(100),
                input_params VARCHAR(100),
                login_count INT
        );
        """)
        conn.commit()
        
        conn.close()

create_user_log()
