

Create table general_info (
    NAME VARCHAR(127),
    ALT_NAME VARCHAR(127),	
    OBJECTID INT UNIQUE,
    ID BIGINT PRIMARY KEY,
    TYPE VARCHAR(127),
    STATUS VARCHAR(10),
    OWNER VARCHAR(32),
    TTL_STAFF INT,	
    TRAUMA VARCHAR(32),
    HELIPAD CHAR,
    BEDS INT,	
    POPULATION INT,	
    NAICS_CODE INT,
    NAICS_DESC VARCHAR(127)
);

Create table dataset_info(
    OBJECTID INT REFERENCES general_info (OBJECTID) ON UPDATE CASCADE ON DELETE CASCADE,
    ID BIGINT REFERENCES general_info (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    SOURCE VARCHAR(127),
    SOURCEDATE TIMESTAMP,
    VAL_METHOD VARCHAR(127),
    VAL_DATE TIMESTAMP
);

Create table contact_info(

    OBJECTID INT REFERENCES general_info (OBJECTID) ON UPDATE CASCADE ON DELETE CASCADE,
    ID BIGINT REFERENCES general_info (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    TELEPHONE VARCHAR(15),	
    WEBSITE VARCHAR(127)
);

Create table address_info(
    OBJECTID INT REFERENCES general_info (OBJECTID) ON UPDATE CASCADE ON DELETE CASCADE,    
    ID BIGINT REFERENCES general_info (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    X DECIMAL(12,8),	
    Y DECIMAL(12,8),
    ADDRESS VARCHAR(127),
    CITY VARCHAR(30),	
    COUNTY VARCHAR(20),	
    COUNTYFIPS INT,
    STATE CHAR(2),
    STATE_ID VARCHAR(15),	
    ST_FIPS INT,
    COUNTRY CHAR(3) DEFAULT 'USA',
    ZIP INT,
    ZIP4 INT,	
    LATITUDE DECIMAL(10,8),
    LONGITUDE DECIMAL(11,8)
);

Create table User_data(
    user_name VARCHAR(50) PRIMARY KEY,
    password VARCHAR(20),
    login_count INT
);
Create table User_Activity_log(
    user_name VARCHAR(50) REFERENCES User_data(user_name) ON UPDATE CASCADE ON DELETE CASCADE,
    query_run INT,
    tables_accessed VARCHAR(50),
    login_count INT
)