CREATE TABLE hosp_general_info(
    NAME VARCHAR(127),
    ALT_NAME VARCHAR(127),	
    OBJECTID INT UNIQUE,
    ID BIGINT PRIMARY KEY,
    TYPE VARCHAR(127),
    STATUS VARCHAR(10),
    OWNER VARCHAR(32),
    TTL_STAFF INT,	
    TRAUMA VARCHAR(50),
    HELIPAD CHAR,
    BEDS INT,	
    POPULATION INT,	
    NAICS_CODE INT,
    NAICS_DESC VARCHAR(127)
);

CREATE TABLE hosp_dataset_info(
    OBJECTID INT REFERENCES hosp_general_info (OBJECTID) ON UPDATE CASCADE ON DELETE CASCADE,
    ID BIGINT REFERENCES hosp_general_info (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    SOURCE VARCHAR(255),
    SOURCEDATE TIMESTAMP,
    VAL_METHOD VARCHAR(127),
    VAL_DATE TIMESTAMP
);

CREATE TABLE hosp_contact_info(
    OBJECTID INT REFERENCES hosp_general_info (OBJECTID) ON UPDATE CASCADE ON DELETE CASCADE,
    ID BIGINT REFERENCES hosp_general_info (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    TELEPHONE VARCHAR(15),	
    WEBSITE VARCHAR(255)
);

CREATE TABLE hosp_address_info(
    OBJECTID INT REFERENCES hosp_general_info (OBJECTID) ON UPDATE CASCADE ON DELETE CASCADE,    
    ID BIGINT REFERENCES hosp_general_info (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    X DECIMAL(12,4),	
    Y DECIMAL(12,4),
    ADDRESS VARCHAR(127),
    CITY VARCHAR(30),	
    COUNTY VARCHAR(20),	
    COUNTYFIPS VARCHAR(20),
    STATE CHAR(2),
    STATE_ID VARCHAR(50),	
    ST_FIPS INT,
    COUNTRY CHAR(3) DEFAULT 'USA',
    ZIP INT,
    ZIP4 VARCHAR(20),	
    LATITUDE DECIMAL(10,4),
    LONGITUDE DECIMAL(11,4)
);

CREATE TABLE nri_version(
    nriId VARCHAR(20) PRIMARY KEY,
    oid SMALLINT UNIQUE,
    nriVer VARCHAR(50)
);

CREATE TABLE nri_state(
    stateabbrv VARCHAR(20) PRIMARY KEY,      
    state VARCHAR(250) UNIQUE,
    statefips VARCHAR(20) UNIQUE
);

CREATE TABLE nri_county(
    stcofips VARCHAR(20) PRIMARY KEY,
    county VARCHAR(250),
    countytype VARCHAR(250),
    countyfips VARCHAR(20),
    stateabbrv VARCHAR(20) REFERENCES nri_state(stateabbrv)    
);

CREATE TABLE nri_demographics(
    nriId VARCHAR(20) PRIMARY KEY REFERENCES nri_version(nriId),
    stcofips VARCHAR(20) REFERENCES nri_county(stcofips),
    population INT,
    buildvalue NUMERIC(17,2),
    agrivalue NUMERIC(17,2),
    area NUMERIC    
);

CREATE TABLE nri_events(
    nriId VARCHAR(20) PRIMARY KEY REFERENCES nri_version(nriId),
    stcofips VARCHAR(20) REFERENCES nri_county(stcofips),
    avlnEvnts NUMERIC(17),
    avlnAfreq NUMERIC,
    cfldEvnts NUMERIC(17),
    cfldAfreq NUMERIC,
    cwavEvnts NUMERIC(17),
    cwavAfreq NUMERIC,
    drgtEvnts NUMERIC(17),
    drgtAfreq NUMERIC,
    erqkEvnts NUMERIC(17),
    erqkAfreq NUMERIC,
    hailEvnts NUMERIC(17),
    hailAfreq NUMERIC,
    hwavEvnts NUMERIC(17),
    hwavAfreq NUMERIC,
    hrcnEvnts NUMERIC(17),
    hrcnAfreq NUMERIC,
    istmEvnts NUMERIC(17),
    istmAfreq NUMERIC,
    lndsEvnts NUMERIC(17),
    lndsAfreq NUMERIC,
    ltngEvnts NUMERIC(17),
    ltngAfreq NUMERIC,
    rfldEvnts NUMERIC(17),
    rfldAfreq NUMERIC,
    swndEvnts NUMERIC(17),
    swndAfreq NUMERIC,
    trndEvnts NUMERIC(17),
    trndAfreq NUMERIC,
    tsunEvnts NUMERIC(17),
    tsunAfreq NUMERIC,
    vlcnEvnts NUMERIC(17),
    vlcnAfreq NUMERIC,
    wfirEvnts NUMERIC(17),
    wfirAfreq NUMERIC,
    wntwEvnts NUMERIC(17),
    wntwAfreq NUMERIC       
);

CREATE TABLE nri_exposure(
    nriId VARCHAR(20) PRIMARY KEY REFERENCES nri_version(nriId),
    stcofips VARCHAR(20) REFERENCES nri_county(stcofips),
    cwavExpa NUMERIC(17,2),
    drgtExpa NUMERIC(17,2),
    hailExpa NUMERIC(17,2),
    hrcnExpa NUMERIC(17,2),
    hwavExpa NUMERIC(17,2),
    rfldExpa NUMERIC(17,2),
    swndExpa NUMERIC(17,2),
    trndExpa NUMERIC(17,2),
    wfirExpa NUMERIC(17,2),
    wntwExpa NUMERIC(17,2),
    avlnExpb NUMERIC(17,2),
    cfldExpb NUMERIC(17,2),
    cwavExpb NUMERIC(17,2),
    erqkExpb NUMERIC(17,2),
    hailExpb NUMERIC(17,2),
    hrcnExpb NUMERIC(17,2),
    hwavExpb NUMERIC(17,2),
    istmExpb NUMERIC(17,2),
    lndsExpb NUMERIC(17,2),
    ltngExpb NUMERIC(17,2),
    rfldExpb NUMERIC(17,2),
    swndExpb NUMERIC(17,2),
    trndExpb NUMERIC(17,2),
    tsunExpb NUMERIC(17,2),
    vlcnExpb NUMERIC(17,2),
    wfirExpb NUMERIC(17,2),
    wntwExpb NUMERIC(17,2),
    avlnExpp NUMERIC,
    cfldExpp NUMERIC,
    cwavExpp NUMERIC,
    erqkExpp NUMERIC,
    hailExpp NUMERIC,
    hrcnExpp NUMERIC,
    hwavExpp NUMERIC,
    istmExpp NUMERIC,
    lndsExpp NUMERIC,
    ltngExpp NUMERIC,
    rfldExpp NUMERIC,
    swndExpp NUMERIC,
    trndExpp NUMERIC,
    tsunExpp NUMERIC,
    vlcnExpp NUMERIC,
    wfirExpp NUMERIC,
    wntwExpp NUMERIC,
    avlnExppe NUMERIC(17,2),
    cfldExppe NUMERIC(17,2),
    cwavExppe NUMERIC(17,2),
    erqkExppe NUMERIC(17,2),
    hailExppe NUMERIC(17,2),
    hrcnExppe NUMERIC(17,2),
    hwavExppe NUMERIC(17,2),
    istmExppe NUMERIC(17,2),
    lndsExppe NUMERIC(17,2),
    ltngExppe NUMERIC(17,2),
    rfldExppe NUMERIC(17,2),
    swndExppe NUMERIC(17,2),
    trndExppe NUMERIC(17,2),
    tsunExppe NUMERIC(17,2),
    vlcnExppe NUMERIC(17,2),
    wfirExppe NUMERIC(17,2),
    wntwExppe NUMERIC(17,2),
    avlnExpt NUMERIC(17,2),
    cfldExpt NUMERIC(17,2),
    cwavExpt NUMERIC(17,2),
    drgtExpt NUMERIC(17,2),
    erqkExpt NUMERIC(17,2),
    hailExpt NUMERIC(17,2),
    hrcnExpt NUMERIC(17,2),
    hwavExpt NUMERIC(17,2),
    istmExpt NUMERIC(17,2),
    lndsExpt NUMERIC(17,2),
    ltngExpt NUMERIC(17,2),
    rfldExpt NUMERIC(17,2),
    swndExpt NUMERIC(17,2),
    trndExpt NUMERIC(17,2),
    tsunExpt NUMERIC(17,2),
    vlcnExpt NUMERIC(17,2),
    wfirExpt NUMERIC(17,2),
    wntwExpt NUMERIC(17,2)      
);

CREATE TABLE nri_historic_loss(
    nriId VARCHAR(20) PRIMARY KEY REFERENCES nri_version(nriId),
    stcofips VARCHAR(20) REFERENCES nri_county(stcofips),
    cwavHlra NUMERIC,
    drgtHlra NUMERIC,
    hailHlra NUMERIC,
    hrcnHlra NUMERIC,
    hwavHlra NUMERIC,
    rfldHlra NUMERIC,
    swndHlra NUMERIC,
    trndHlra NUMERIC,
    wfirHlra NUMERIC,
    wntwHlra NUMERIC,
    avlnHlrb NUMERIC,
    cfldHlrb NUMERIC,
    cwavHlrb NUMERIC,
    erqkHlrb NUMERIC,
    hailHlrb NUMERIC,
    hrcnHlrb NUMERIC,
    hwavHlrb NUMERIC,
    istmHlrb NUMERIC,
    lndsHlrb NUMERIC,
    ltngHlrb NUMERIC,
    rfldHlrb NUMERIC,
    swndHlrb NUMERIC,
    trndHlrb NUMERIC,
    tsunHlrb NUMERIC,
    vlcnHlrb NUMERIC,
    wfirHlrb NUMERIC,
    wntwHlrb NUMERIC,
    avlnHlrp NUMERIC,
    cfldHlrp NUMERIC,
    cwavHlrp NUMERIC,
    erqkHlrp NUMERIC,
    hailHlrp NUMERIC,
    hrcnHlrp NUMERIC,
    hwavHlrp NUMERIC,
    istmHlrp NUMERIC,
    lndsHlrp NUMERIC,
    ltngHlrp NUMERIC,
    rfldHlrp NUMERIC,
    swndHlrp NUMERIC,
    trndHlrp NUMERIC,
    tsunHlrp NUMERIC,
    vlcnHlrp NUMERIC,
    wfirHlrp NUMERIC,
    wntwHlrp NUMERIC,
    avlnHlrr VARCHAR(50),
    cfldHlrr VARCHAR(50),
    cwavHlrr VARCHAR(50),
    drgtHlrr VARCHAR(50),
    erqkHlrr VARCHAR(50),
    hailHlrr VARCHAR(50),
    hrcnHlrr VARCHAR(50),
    hwavHlrr VARCHAR(50),
    istmHlrr VARCHAR(50),
    lndsHlrr VARCHAR(50),
    ltngHlrr VARCHAR(50),
    rfldHlrr VARCHAR(50),
    swndHlrr VARCHAR(50),
    trndHlrr VARCHAR(50),
    tsunHlrr VARCHAR(50),
    vlcnHlrr VARCHAR(50),
    wfirHlrr VARCHAR(50),
    wntwHlrr VARCHAR(50) 
);

CREATE TABLE nri_expected_loss(
    nriId VARCHAR(20) PRIMARY KEY REFERENCES nri_version(nriId),
    stcofips VARCHAR(20) REFERENCES nri_county(stcofips),
    ealValt NUMERIC(17,2),
    ealValb NUMERIC(17,2),
    ealValp NUMERIC,
    ealValpe NUMERIC(17,2),
    ealVala NUMERIC(17,2),
    cwavEala NUMERIC(17,2),
    drgtEala NUMERIC(17,2),
    hailEala NUMERIC(17,2),
    hrcnEala NUMERIC(17,2),
    hwavEala NUMERIC(17,2),
    rfldEala NUMERIC(17,2),
    swndEala NUMERIC(17,2),
    trndEala NUMERIC(17,2),
    wfirEala NUMERIC(17,2),
    wntwEala NUMERIC(17,2),
    avlnEalb NUMERIC(17,2),
    cfldEalb NUMERIC(17,2),
    cwavEalb NUMERIC(17,2),
    erqkEalb NUMERIC(17,2),
    hailEalb NUMERIC(17,2),
    hrcnEalb NUMERIC(17,2),
    hwavEalb NUMERIC(17,2),
    istmEalb NUMERIC(17,2),
    lndsEalb NUMERIC(17,2),
    ltngEalb NUMERIC(17,2),
    rfldEalb NUMERIC(17,2),
    swndEalb NUMERIC(17,2),
    trndEalb NUMERIC(17,2),
    tsunEalb NUMERIC(17,2),
    vlcnEalb NUMERIC(17,2),
    wfirEalb NUMERIC(17,2),
    wntwEalb NUMERIC(17,2),
    avlnEalp NUMERIC,
    cfldEalp NUMERIC,
    cwavEalp NUMERIC,
    erqkEalp NUMERIC,
    hailEalp NUMERIC,
    hrcnEalp NUMERIC,
    hwavEalp NUMERIC,
    istmEalp NUMERIC,
    lndsEalp NUMERIC,
    ltngEalp NUMERIC,
    rfldEalp NUMERIC,
    swndEalp NUMERIC,
    trndEalp NUMERIC,
    tsunEalp NUMERIC,
    vlcnEalp NUMERIC,
    wfirEalp NUMERIC,
    wntwEalp NUMERIC,
    avlnEalpe NUMERIC(17,2),
    cfldEalpe NUMERIC(17,2),
    cwavEalpe NUMERIC(17,2),
    erqkEalpe NUMERIC(17,2),
    hailEalpe NUMERIC(17,2),
    hrcnEalpe NUMERIC(17,2),
    hwavEalpe NUMERIC(17,2),
    istmEalpe NUMERIC(17,2),
    lndsEalpe NUMERIC(17,2),
    ltngEalpe NUMERIC(17,2),
    rfldEalpe NUMERIC(17,2),
    swndEalpe NUMERIC(17,2),
    trndEalpe NUMERIC(17,2),
    tsunEalpe NUMERIC(17,2),
    vlcnEalpe NUMERIC(17,2),
    wfirEalpe NUMERIC(17,2),
    wntwEalpe NUMERIC(17,2),
    avlnEalr VARCHAR(50),
    cfldEalr VARCHAR(50),
    cwavEalr VARCHAR(50),
    drgtEalr VARCHAR(50),
    erqkEalr VARCHAR(50),
    hailEalr VARCHAR(50),
    hrcnEalr VARCHAR(50),
    hwavEalr VARCHAR(50),
    istmEalr VARCHAR(50),
    lndsEalr VARCHAR(50),
    ltngEalr VARCHAR(50),
    rfldEalr VARCHAR(50),
    swndEalr VARCHAR(50),
    trndEalr VARCHAR(50),
    tsunEalr VARCHAR(50),
    vlcnEalr VARCHAR(50),
    wfirEalr VARCHAR(50),
    wntwEalr VARCHAR(50),
    avlnEals NUMERIC(17,2),
    cfldEals NUMERIC(17,2),
    cwavEals NUMERIC(17,2),
    drgtEals NUMERIC(17,2),
    erqkEals NUMERIC(17,2),
    hailEals NUMERIC(17,2),
    hrcnEals NUMERIC(17,2),
    hwavEals NUMERIC(17,2),
    istmEals NUMERIC(17,2),
    lndsEals NUMERIC(17,2),
    ltngEals NUMERIC(17,2),
    rfldEals NUMERIC(17,2),
    swndEals NUMERIC(17,2),
    trndEals NUMERIC(17,2),
    tsunEals NUMERIC(17,2),
    vlcnEals NUMERIC(17,2),
    wfirEals NUMERIC(17,2),
    wntwEals NUMERIC(17,2),
    avlnEalt NUMERIC(17,2),
    cfldEalt NUMERIC(17,2),
    cwavEalt NUMERIC(17,2),
    drgtEalt NUMERIC(17,2),
    erqkEalt NUMERIC(17,2),
    hailEalt NUMERIC(17,2),
    hrcnEalt NUMERIC(17,2),
    hwavEalt NUMERIC(17,2),
    istmEalt NUMERIC(17,2),
    lndsEalt NUMERIC(17,2),
    ltngEalt NUMERIC(17,2),
    rfldEalt NUMERIC(17,2),
    swndEalt NUMERIC(17,2),
    trndEalt NUMERIC(17,2),
    tsunEalt NUMERIC(17,2),
    vlcnEalt NUMERIC(17,2),
    wfirEalt NUMERIC(17,2),
    wntwEalt NUMERIC(17,2)
);

CREATE TABLE nri_risk(
    nriId VARCHAR(20) PRIMARY KEY REFERENCES nri_version(nriId),
    stcofips VARCHAR(20) REFERENCES nri_county(stcofips),
    riskRatng VARCHAR(50),
    avlnRiskr VARCHAR(50),
    cfldRiskr VARCHAR(50),
    cwavRiskr VARCHAR(50),
    drgtRiskr VARCHAR(50),
    erqkRiskr VARCHAR(50),
    hailRiskr VARCHAR(50),
    hrcnRiskr VARCHAR(50),
    hwavRiskr VARCHAR(50),
    istmRiskr VARCHAR(50),
    lndsRiskr VARCHAR(50),
    ltngRiskr VARCHAR(50),
    rfldRiskr VARCHAR(50),
    swndRiskr VARCHAR(50),
    trndRiskr VARCHAR(50),
    tsunRiskr VARCHAR(50),
    vlcnRiskr VARCHAR(50),
    wfirRiskr VARCHAR(50),
    wntwRiskr VARCHAR(50),
    riskScore NUMERIC,
    avlnRisks NUMERIC,
    cfldRisks NUMERIC,
    cwavRisks NUMERIC,
    drgtRisks NUMERIC,
    erqkRisks NUMERIC,
    hailRisks NUMERIC,
    hrcnRisks NUMERIC,
    hwavRisks NUMERIC,
    istmRisks NUMERIC,
    lndsRisks NUMERIC,
    ltngRisks NUMERIC,
    rfldRisks NUMERIC,
    swndRisks NUMERIC,
    trndRisks NUMERIC,
    tsunRisks NUMERIC,
    vlcnRisks NUMERIC,
    wfirRisks NUMERIC,
    wntwRisks NUMERIC
);

CREATE TABLE nri_percentiles(
    nriId VARCHAR(20) PRIMARY KEY REFERENCES nri_version(nriId),
    stcofips VARCHAR(20) REFERENCES nri_county(stcofips),
    riskNpctl NUMERIC,
    riskSpctl NUMERIC,
    ealNpctl NUMERIC,
    ealSpctl NUMERIC
);

CREATE TABLE user_data(
    user_name VARCHAR(50) PRIMARY KEY,
    login_count INT
);

CREATE TABLE user_activity_log(
    user_name VARCHAR(50) REFERENCES User_data(user_name) ON UPDATE CASCADE ON DELETE CASCADE,
    query_run INT,
    tables_accessed VARCHAR(100),
    input_params VARCHAR(100),
    login_count INT
);
